#
# http://travis-ci.org configuration file for openMVG
#

language: cpp

compiler:
  - gcc
  #- clang: #Consider clang later, since cereal does not build fine on the clang CI version
  #  - "3.3"

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- cmake # Manually install latest version (>=3.0)
      - libboost1.55-all-dev
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8
      - libatlas-base-dev
      - libsuitesparse-dev

env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
    - BUILD_TYPE="Release"
    - BUILD_SYSTEM="`uname -s`"
    - BUILD_PROCESSOR="`uname -p`"
    - DEPS_INSTALL_DIR=${TRAVIS_BUILD_DIR}/install-deps
    - INSTALL_DIR=${TRAVIS_BUILD_DIR}/install
    - TARGET_FULL_NAME=${TRAVIS_TAG}
    - TARGET_NAME=$(echo ${TARGET_FULL_NAME} | cut -d "-" -f1)
    - TARGET_VERSION=$(echo ${TARGET_FULL_NAME} | cut -d "-" -f2)
    - INSTALL_ARCHIVE_FILENAME=${TARGET_FULL_NAME}.tgz

before_install:
 - date -u
 - uname -a
 - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
     lsb_release -a;
   elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
     sw_vers -productVersion;
   fi

install:
 - ./ci/install-cmake.sh

script:
 - mkdir -p ${INSTALL_DIR}/${TARGET_FULL_NAME}
 - ./ci/install-${TARGET_NAME}.sh ${TARGET_VERSION} ${INSTALL_DIR}/${TARGET_FULL_NAME}

before_deploy:
- . ./ci/env.sh
- cd ${INSTALL_DIR}
- tar -czvf ${INSTALL_ARCHIVE_FILENAME} ${TARGET_FULL_NAME}

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_RELEASE_API_KEY}
  file: ${INSTALL_DIR}/${INSTALL_ARCHIVE_FILENAME}
  skip_cleanup: true
  on:
    tags: true
